import { shuffle } from "../shared/lib/shuffle";

export type WordLevel = "A1" | "A2" | "B1" | "B2" | "C1" | "C2";

export interface WordEntry {
  word: string;
  translation: string;
}

export const WORD_LEVELS: WordLevel[] = ["A1", "A2", "B1", "B2", "C1", "C2"];

export const WORDS_BY_LEVEL: Record<WordLevel, WordEntry[]> = {
  A1: [
    { word: "hello", translation: "привіт" },
    { word: "goodbye", translation: "до побачення" },
    { word: "please", translation: "будь ласка" },
    { word: "thanks", translation: "дякую" },
    { word: "sorry", translation: "вибач" },
    { word: "yes", translation: "так" },
    { word: "no", translation: "ні" },
    { word: "water", translation: "вода" },
    { word: "food", translation: "їжа" },
    { word: "bread", translation: "хліб" },
    { word: "milk", translation: "молоко" },
    { word: "apple", translation: "яблуко" },
    { word: "tea", translation: "чай" },
    { word: "coffee", translation: "кава" },
    { word: "egg", translation: "яйце" },
    { word: "meat", translation: "м'ясо" },
    { word: "fish", translation: "риба" },
    { word: "rice", translation: "рис" },
    { word: "salt", translation: "сіль" },
    { word: "sugar", translation: "цукор" },
    { word: "mother", translation: "мама" },
    { word: "father", translation: "тато" },
    { word: "sister", translation: "сестра" },
    { word: "brother", translation: "брат" },
    { word: "family", translation: "сім'я" },
    { word: "friend", translation: "друг" },
    { word: "baby", translation: "немовля" },
    { word: "boy", translation: "хлопчик" },
    { word: "girl", translation: "дівчинка" },
    { word: "man", translation: "чоловік" },
    { word: "woman", translation: "жінка" },
    { word: "house", translation: "дім" },
    { word: "room", translation: "кімната" },
    { word: "door", translation: "двері" },
    { word: "window", translation: "вікно" },
    { word: "table", translation: "стіл" },
    { word: "chair", translation: "стілець" },
    { word: "bed", translation: "ліжко" },
    { word: "book", translation: "книга" },
    { word: "pen", translation: "ручка" },
    { word: "paper", translation: "папір" },
    { word: "cat", translation: "кіт" },
    { word: "dog", translation: "собака" },
    { word: "bird", translation: "птах" },
    { word: "horse", translation: "кінь" },
    { word: "cow", translation: "корова" },
    { word: "pig", translation: "свиня" },
    { word: "mouse", translation: "миша" },
    { word: "tree", translation: "дерево" },
    { word: "flower", translation: "квітка" },
    { word: "sun", translation: "сонце" },
    { word: "moon", translation: "місяць" },
    { word: "star", translation: "зірка" },
    { word: "sky", translation: "небо" },
    { word: "day", translation: "день" },
    { word: "night", translation: "ніч" },
    { word: "morning", translation: "ранок" },
    { word: "evening", translation: "вечір" },
    { word: "week", translation: "тиждень" },
    { word: "year", translation: "рік" },
    { word: "red", translation: "червоний" },
    { word: "blue", translation: "синій" },
    { word: "green", translation: "зелений" },
    { word: "yellow", translation: "жовтий" },
    { word: "black", translation: "чорний" },
    { word: "white", translation: "білий" },
    { word: "big", translation: "великий" },
    { word: "small", translation: "малий" },
    { word: "hot", translation: "гарячий" },
    { word: "cold", translation: "холодний" },
    { word: "go", translation: "йти" },
    { word: "come", translation: "приходити" },
    { word: "eat", translation: "їсти" },
    { word: "drink", translation: "пити" },
    { word: "sleep", translation: "спати" },
    { word: "read", translation: "читати" },
    { word: "write", translation: "писати" },
    { word: "speak", translation: "говорити" },
    { word: "listen", translation: "слухати" },
    { word: "walk", translation: "ходити" },
    { word: "run", translation: "бігти" },
    { word: "see", translation: "бачити" },
    { word: "hear", translation: "чути" },
    { word: "know", translation: "знати" },
    { word: "think", translation: "думати" },
    { word: "want", translation: "хотіти" },
    { word: "like", translation: "подобатися" },
    { word: "love", translation: "кохати" },
    { word: "help", translation: "допомагати" },
    { word: "work", translation: "працювати" },
    { word: "school", translation: "школа" },
    { word: "teacher", translation: "вчитель" },
    { word: "student", translation: "учень" },
    { word: "name", translation: "ім'я" },
    { word: "city", translation: "місто" },
    { word: "country", translation: "країна" },
    { word: "time", translation: "час" },
    { word: "money", translation: "гроші" },
    { word: "phone", translation: "телефон" },
    { word: "car", translation: "машина" },
    { word: "happy", translation: "щасливий" },
    { word: "sad", translation: "сумний" },
    { word: "good", translation: "добрий" },
    { word: "bad", translation: "поганий" },
    { word: "new", translation: "новий" },
    { word: "old", translation: "старий" },
    { word: "young", translation: "молодий" },
  ],
  A2: [
    { word: "weather", translation: "погода" },
    { word: "holiday", translation: "свято" },
    { word: "journey", translation: "подорож" },
    { word: "arrive", translation: "прибувати" },
    { word: "decide", translation: "вирішувати" },
    { word: "improve", translation: "покращувати" },
    { word: "describe", translation: "описувати" },
    { word: "suggest", translation: "пропонувати" },
    { word: "explain", translation: "пояснювати" },
    { word: "remember", translation: "пам'ятати" },
    { word: "forget", translation: "забувати" },
    { word: "invite", translation: "запрошувати" },
    { word: "promise", translation: "обіцяти" },
    { word: "borrow", translation: "позичати" },
    { word: "lend", translation: "давати в борг" },
    { word: "spend", translation: "витрачати" },
    { word: "save", translation: "зберігати" },
    { word: "choose", translation: "обирати" },
    { word: "prefer", translation: "надавати перевагу" },
    { word: "prepare", translation: "готувати" },
    { word: "healthy", translation: "здоровий" },
    { word: "dangerous", translation: "небезпечний" },
    { word: "careful", translation: "обережний" },
    { word: "polite", translation: "ввічливий" },
    { word: "quiet", translation: "тихий" },
    { word: "noisy", translation: "гучний" },
    { word: "famous", translation: "відомий" },
    { word: "successful", translation: "успішний" },
    { word: "patient", translation: "терплячий" },
    { word: "honest", translation: "чесний" },
    { word: "laugh", translation: "сміятися" },
    { word: "cry", translation: "плакати" },
    { word: "worry", translation: "хвилюватися" },
    { word: "enjoy", translation: "насолоджуватися" },
    { word: "expect", translation: "очікувати" },
    { word: "believe", translation: "вірити" },
    { word: "receive", translation: "отримувати" },
    { word: "provide", translation: "забезпечувати" },
    { word: "discuss", translation: "обговорювати" },
    { word: "compare", translation: "порівнювати" },
    { word: "buy", translation: "купувати" },
    { word: "sell", translation: "продавати" },
    { word: "pay", translation: "платити" },
    { word: "deliver", translation: "доставляти" },
    { word: "order", translation: "замовляти" },
    { word: "return", translation: "повертати" },
    { word: "exchange", translation: "обмінювати" },
    { word: "refund", translation: "відшкодування" },
    { word: "bargain", translation: "торгуватися" },
    { word: "ticket", translation: "квиток" },
    { word: "passport", translation: "паспорт" },
    { word: "luggage", translation: "багаж" },
    { word: "hotel", translation: "готель" },
    { word: "airport", translation: "аеропорт" },
    { word: "station", translation: "станція" },
    { word: "guide", translation: "гід" },
    { word: "tour", translation: "екскурсія" },
    { word: "hobby", translation: "хобі" },
    { word: "painting", translation: "живопис" },
    { word: "dancing", translation: "танці" },
    { word: "swimming", translation: "плавання" },
    { word: "running", translation: "біг" },
    { word: "cycling", translation: "велоспорт" },
    { word: "cooking", translation: "готування" },
    { word: "baking", translation: "випікання" },
    { word: "gardening", translation: "садівництво" },
    { word: "fishing", translation: "риболовля" },
    { word: "forecast", translation: "прогноз" },
    { word: "rainy", translation: "дощовий" },
    { word: "cloudy", translation: "хмарний" },
    { word: "windy", translation: "вітряний" },
    { word: "snowy", translation: "сніжний" },
    { word: "storm", translation: "буря" },
    { word: "thunder", translation: "грім" },
    { word: "lightning", translation: "блискавка" },
    { word: "angry", translation: "сердитий" },
    { word: "tired", translation: "втомлений" },
    { word: "bored", translation: "нудьгуючий" },
    { word: "excited", translation: "схвильований" },
    { word: "nervous", translation: "нервовий" },
    { word: "surprised", translation: "здивований" },
    { word: "confused", translation: "спантеличений" },
    { word: "proud", translation: "гордий" },
    { word: "jealous", translation: "заздрісний" },
    { word: "boss", translation: "начальник" },
    { word: "colleague", translation: "колега" },
    { word: "salary", translation: "зарплата" },
    { word: "meeting", translation: "зустріч" },
    { word: "deadline", translation: "дедлайн" },
    { word: "project", translation: "проєкт" },
    { word: "client", translation: "клієнт" },
    { word: "report", translation: "звіт" },
    { word: "office", translation: "офіс" },
    { word: "manager", translation: "менеджер" },
  ],
  B1: [
    { word: "achieve", translation: "досягати" },
    { word: "advantage", translation: "перевага" },
    { word: "affect", translation: "впливати" },
    { word: "approach", translation: "підхід" },
    { word: "assume", translation: "припускати" },
    { word: "aware", translation: "обізнаний" },
    { word: "benefit", translation: "користь" },
    { word: "challenge", translation: "виклик" },
    { word: "conclude", translation: "робити висновок" },
    { word: "consequence", translation: "наслідок" },
    { word: "consider", translation: "розглядати" },
    { word: "contain", translation: "містити" },
    { word: "contribute", translation: "сприяти" },
    { word: "convince", translation: "переконувати" },
    { word: "define", translation: "визначати" },
    { word: "demonstrate", translation: "демонструвати" },
    { word: "determine", translation: "встановлювати" },
    { word: "develop", translation: "розвивати" },
    { word: "efficient", translation: "ефективний" },
    { word: "emphasize", translation: "наголошувати" },
    { word: "establish", translation: "засновувати" },
    { word: "evaluate", translation: "оцінювати" },
    { word: "evidence", translation: "доказ" },
    { word: "examine", translation: "досліджувати" },
    { word: "expand", translation: "розширювати" },
    { word: "familiar", translation: "знайомий" },
    { word: "feature", translation: "особливість" },
    { word: "focus", translation: "зосереджуватися" },
    { word: "generate", translation: "генерувати" },
    { word: "identify", translation: "ідентифікувати" },
    { word: "impact", translation: "вплив" },
    { word: "imply", translation: "мати на увазі" },
    { word: "indicate", translation: "вказувати" },
    { word: "influence", translation: "впливати" },
    { word: "involve", translation: "залучати" },
    { word: "maintain", translation: "підтримувати" },
    { word: "measure", translation: "вимірювати" },
    { word: "occur", translation: "відбуватися" },
    { word: "participate", translation: "брати участь" },
    { word: "policy", translation: "політика" },
    { word: "principle", translation: "принцип" },
    { word: "priority", translation: "пріоритет" },
    { word: "procedure", translation: "процедура" },
    { word: "process", translation: "процес" },
    { word: "promote", translation: "просувати" },
    { word: "propose", translation: "пропонувати" },
    { word: "purchase", translation: "придбання" },
    { word: "pursue", translation: "переслідувати" },
    { word: "reduce", translation: "зменшувати" },
    { word: "reflect", translation: "відображати" },
    { word: "relate", translation: "стосуватися" },
    { word: "remain", translation: "залишатися" },
    { word: "require", translation: "вимагати" },
    { word: "research", translation: "дослідження" },
    { word: "respond", translation: "відповідати" },
    { word: "reveal", translation: "розкривати" },
    { word: "satisfy", translation: "задовольняти" },
    { word: "secure", translation: "безпечний" },
    { word: "significant", translation: "значний" },
    { word: "similar", translation: "схожий" },
    { word: "solve", translation: "вирішувати" },
    { word: "source", translation: "джерело" },
    { word: "specific", translation: "конкретний" },
    { word: "strategy", translation: "стратегія" },
    { word: "structure", translation: "структура" },
    { word: "sufficient", translation: "достатній" },
    { word: "suggest", translation: "пропонувати" },
    { word: "summary", translation: "підсумок" },
    { word: "support", translation: "підтримка" },
    { word: "attitude", translation: "ставлення" },
    { word: "authority", translation: "влада" },
    { word: "capable", translation: "здатний" },
    { word: "category", translation: "категорія" },
    { word: "circumstance", translation: "обставина" },
    { word: "commit", translation: "зобов'язуватися" },
    { word: "community", translation: "спільнота" },
    { word: "concern", translation: "занепокоєння" },
    { word: "conduct", translation: "проводити" },
    { word: "confirm", translation: "підтверджувати" },
    { word: "conflict", translation: "конфлікт" },
    { word: "contract", translation: "контракт" },
    { word: "control", translation: "контроль" },
    { word: "coordinate", translation: "координувати" },
    { word: "create", translation: "створювати" },
    { word: "culture", translation: "культура" },
    { word: "current", translation: "поточний" },
    { word: "debate", translation: "дебати" },
    { word: "decline", translation: "спад" },
    { word: "demand", translation: "попит" },
    { word: "design", translation: "дизайн" },
    { word: "detect", translation: "виявляти" },
    { word: "distinguish", translation: "розрізняти" },
    { word: "distribute", translation: "розподіляти" },
    { word: "diverse", translation: "різноманітний" },
    { word: "estimate", translation: "оцінювати" },
    { word: "function", translation: "функціонувати" },
    { word: "illustrate", translation: "ілюструвати" },
    { word: "inspect", translation: "перевіряти" },
    { word: "investigate", translation: "розслідувати" },
    { word: "justify", translation: "виправдовувати" },
  ],
  B2: [
    { word: "abundant", translation: "рясний" },
    { word: "acknowledge", translation: "визнавати" },
    { word: "adjacent", translation: "суміжний" },
    { word: "advocate", translation: "прихильник" },
    { word: "alleviate", translation: "полегшувати" },
    { word: "ambiguous", translation: "двозначний" },
    { word: "anticipate", translation: "передбачати" },
    { word: "arbitrary", translation: "довільний" },
    { word: "articulate", translation: "виразно висловлювати" },
    { word: "attribute", translation: "приписувати" },
    { word: "coherent", translation: "послідовний" },
    { word: "compelling", translation: "переконливий" },
    { word: "comprehensive", translation: "всеосяжний" },
    { word: "conducive", translation: "сприятливий" },
    { word: "consensus", translation: "консенсус" },
    { word: "constitute", translation: "становити" },
    { word: "contemplate", translation: "обдумувати" },
    { word: "contradict", translation: "суперечити" },
    { word: "controversial", translation: "суперечливий" },
    { word: "crucial", translation: "вирішальний" },
    { word: "cynical", translation: "цинічний" },
    { word: "deteriorate", translation: "погіршуватися" },
    { word: "deviate", translation: "відхилятися" },
    { word: "diminish", translation: "зменшувати" },
    { word: "discern", translation: "розрізняти" },
    { word: "disclose", translation: "розкривати" },
    { word: "disparity", translation: "нерівність" },
    { word: "disseminate", translation: "поширювати" },
    { word: "elaborate", translation: "детально розробляти" },
    { word: "elucidate", translation: "роз'яснювати" },
    { word: "embody", translation: "втілювати" },
    { word: "endeavor", translation: "намагатися" },
    { word: "enhance", translation: "покращувати" },
    { word: "entail", translation: "тягнути за собою" },
    { word: "epitome", translation: "втілення" },
    { word: "equitable", translation: "справедливий" },
    { word: "exacerbate", translation: "загострювати" },
    { word: "exemplify", translation: "наводити приклад" },
    { word: "feasible", translation: "здійсненний" },
    { word: "formulate", translation: "формулювати" },
    { word: "formidable", translation: "грізний" },
    { word: "foster", translation: "сприяти" },
    { word: "garner", translation: "накопичувати" },
    { word: "hamper", translation: "перешкоджати" },
    { word: "hinder", translation: "заважати" },
    { word: "imminent", translation: "неминучий" },
    { word: "imperative", translation: "вкрай важливий" },
    { word: "implement", translation: "впроваджувати" },
    { word: "implication", translation: "наслідок" },
    { word: "impose", translation: "нав'язувати" },
    { word: "incentive", translation: "стимул" },
    { word: "incidental", translation: "побічний" },
    { word: "inevitable", translation: "неминучий" },
    { word: "infer", translation: "робити висновок" },
    { word: "inherent", translation: "притаманний" },
    { word: "inhibit", translation: "стримувати" },
    { word: "initiate", translation: "ініціювати" },
    { word: "innovate", translation: "впроваджувати інновації" },
    { word: "integral", translation: "невід'ємний" },
    { word: "integrate", translation: "інтегрувати" },
    { word: "integrity", translation: "цілісність" },
    { word: "intervene", translation: "втручатися" },
    { word: "intricate", translation: "заплутаний" },
    { word: "intrinsic", translation: "внутрішній" },
    { word: "invoke", translation: "викликати" },
    { word: "irreplaceable", translation: "незамінний" },
    { word: "jeopardize", translation: "наражати на небезпеку" },
    { word: "legitimate", translation: "законний" },
    { word: "leverage", translation: "використовувати" },
    { word: "manifest", translation: "проявляти" },
    { word: "meticulous", translation: "ретельний" },
    { word: "mitigate", translation: "пом'якшувати" },
    { word: "momentum", translation: "імпульс" },
    { word: "monotonous", translation: "одноманітний" },
    { word: "negotiate", translation: "вести переговори" },
    { word: "notion", translation: "поняття" },
    { word: "nuance", translation: "відтінок" },
    { word: "obscure", translation: "неясний" },
    { word: "obsolete", translation: "застарілий" },
    { word: "offset", translation: "компенсувати" },
    { word: "ongoing", translation: "триваючий" },
    { word: "optimum", translation: "оптимальний" },
    { word: "paradigm", translation: "парадигма" },
    { word: "paramount", translation: "першорядний" },
    { word: "pervasive", translation: "всеохопний" },
    { word: "plausible", translation: "правдоподібний" },
    { word: "ponder", translation: "розмірковувати" },
    { word: "pragmatic", translation: "прагматичний" },
    { word: "precedent", translation: "прецедент" },
    { word: "predominant", translation: "переважаючий" },
    { word: "prevail", translation: "переважати" },
    { word: "profound", translation: "глибокий" },
    { word: "prohibit", translation: "забороняти" },
    { word: "proliferate", translation: "поширюватися" },
    { word: "proximity", translation: "близькість" },
    { word: "prudent", translation: "розсудливий" },
    { word: "ramification", translation: "наслідок" },
    { word: "reciprocal", translation: "взаємний" },
    { word: "redundant", translation: "надлишковий" },
    { word: "reinforce", translation: "підкріплювати" },
    { word: "resilient", translation: "стійкий" },
    { word: "scrutiny", translation: "ретельна перевірка" },
  ],
  C1: [
    { word: "abate", translation: "слабшати" },
    { word: "aberration", translation: "відхилення" },
    { word: "abhor", translation: "ненавидіти" },
    { word: "abstruse", translation: "незрозумілий" },
    { word: "accolade", translation: "визнання" },
    { word: "acquiesce", translation: "погоджуватися" },
    { word: "acrimonious", translation: "уїдливий" },
    { word: "acumen", translation: "проникливість" },
    { word: "adamant", translation: "непохитний" },
    { word: "admonish", translation: "дорікати" },
    { word: "adroit", translation: "спритний" },
    { word: "affable", translation: "привітний" },
    { word: "affront", translation: "образа" },
    { word: "alacrity", translation: "жвавість" },
    { word: "allegory", translation: "алегорія" },
    { word: "allude", translation: "натякати" },
    { word: "altruistic", translation: "альтруїстичний" },
    { word: "amalgamate", translation: "об'єднувати" },
    { word: "ambivalent", translation: "двоїстий" },
    { word: "ameliorate", translation: "покращувати" },
    { word: "amenable", translation: "поступливий" },
    { word: "amiable", translation: "доброзичливий" },
    { word: "anachronism", translation: "анахронізм" },
    { word: "anathema", translation: "прокляття" },
    { word: "animosity", translation: "ворожість" },
    { word: "anomalous", translation: "аномальний" },
    { word: "antipathy", translation: "антипатія" },
    { word: "apathy", translation: "апатія" },
    { word: "apex", translation: "вершина" },
    { word: "apocryphal", translation: "сумнівний" },
    { word: "apostate", translation: "відступник" },
    { word: "apotheosis", translation: "апофеоз" },
    { word: "appease", translation: "умиротворяти" },
    { word: "apprehension", translation: "побоювання" },
    { word: "approbation", translation: "схвалення" },
    { word: "arcane", translation: "таємничий" },
    { word: "archaic", translation: "архаїчний" },
    { word: "arduous", translation: "важкий" },
    { word: "ascertain", translation: "з'ясовувати" },
    { word: "ascetic", translation: "аскетичний" },
    { word: "assiduous", translation: "старанний" },
    { word: "assuage", translation: "заспокоювати" },
    { word: "astute", translation: "проникливий" },
    { word: "attrition", translation: "виснаження" },
    { word: "audacious", translation: "зухвалий" },
    { word: "augment", translation: "примножувати" },
    { word: "auspicious", translation: "сприятливий" },
    { word: "austere", translation: "суворий" },
    { word: "autonomous", translation: "автономний" },
    { word: "avarice", translation: "жадібність" },
    { word: "aversion", translation: "відраза" },
    { word: "balk", translation: "відмовлятися" },
    { word: "banal", translation: "банальний" },
    { word: "bellicose", translation: "войовничий" },
    { word: "benevolent", translation: "доброзичливий" },
    { word: "bequeath", translation: "заповідати" },
    { word: "bereft", translation: "позбавлений" },
    { word: "berate", translation: "лаяти" },
    { word: "beseech", translation: "благати" },
    { word: "blatant", translation: "відвертий" },
    { word: "bolster", translation: "зміцнювати" },
    { word: "bombastic", translation: "пишномовний" },
    { word: "boorish", translation: "грубий" },
    { word: "brusque", translation: "різкий" },
    { word: "bucolic", translation: "пасторальний" },
    { word: "burgeon", translation: "розквітати" },
    { word: "burnish", translation: "полірувати" },
    { word: "cajole", translation: "улещувати" },
    { word: "callous", translation: "бездушний" },
    { word: "candid", translation: "відвертий" },
    { word: "capricious", translation: "примхливий" },
    { word: "castigate", translation: "суворо критикувати" },
    { word: "catalyst", translation: "каталізатор" },
    { word: "caustic", translation: "їдкий" },
    { word: "censure", translation: "осуд" },
    { word: "chastise", translation: "карати" },
    { word: "chicanery", translation: "шахрайство" },
    { word: "circumspect", translation: "обачний" },
    { word: "clandestine", translation: "таємний" },
    { word: "coalesce", translation: "об'єднуватися" },
    { word: "cogent", translation: "переконливий" },
    { word: "commensurate", translation: "пропорційний" },
    { word: "compunction", translation: "докори сумління" },
    { word: "conciliatory", translation: "примирливий" },
    { word: "conflate", translation: "об'єднувати" },
    { word: "connoisseur", translation: "знавець" },
    { word: "contrite", translation: "розкаяний" },
    { word: "copious", translation: "рясний" },
    { word: "corroborate", translation: "підтверджувати" },
    { word: "credulous", translation: "довірливий" },
    { word: "culminate", translation: "досягати кульмінації" },
    { word: "cursory", translation: "поверховий" },
    { word: "dearth", translation: "нестача" },
    { word: "debilitate", translation: "виснажувати" },
    { word: "decorum", translation: "пристойність" },
    { word: "deference", translation: "повага" },
    { word: "delineate", translation: "окреслювати" },
    { word: "denigrate", translation: "принижувати" },
    { word: "deride", translation: "висміювати" },
    { word: "desultory", translation: "безсистемний" },
  ],
  C2: [
    { word: "abjure", translation: "зректися" },
    { word: "abnegate", translation: "відмовлятися" },
    { word: "abrogate", translation: "скасовувати" },
    { word: "abscond", translation: "втекти" },
    { word: "abstemious", translation: "поміркований" },
    { word: "accede", translation: "погоджуватися" },
    { word: "acerbic", translation: "уїдливий" },
    { word: "acolyte", translation: "послідовник" },
    { word: "acrimony", translation: "жовчність" },
    { word: "acuity", translation: "гострота" },
    { word: "adjure", translation: "заклинати" },
    { word: "adscititious", translation: "додатковий" },
    { word: "adulation", translation: "лестощі" },
    { word: "aegis", translation: "заступництво" },
    { word: "aesthete", translation: "естет" },
    { word: "aggrandizement", translation: "піднесення" },
    { word: "alembic", translation: "перегінний куб" },
    { word: "alluvial", translation: "алювіальний" },
    { word: "amanuensis", translation: "переписувач" },
    { word: "ambrosial", translation: "божественний" },
    { word: "anodyne", translation: "заспокійливий" },
    { word: "anomie", translation: "аномія" },
    { word: "antebellum", translation: "довоєнний" },
    { word: "antediluvian", translation: "допотопний" },
    { word: "apogee", translation: "апогей" },
    { word: "apoplectic", translation: "розлючений" },
    { word: "apostasy", translation: "віровідступництво" },
    { word: "apothegm", translation: "афоризм" },
    { word: "apposite", translation: "доречний" },
    { word: "apprise", translation: "повідомляти" },
    { word: "apropos", translation: "до речі" },
    { word: "aquiline", translation: "орлиний" },
    { word: "arbiter", translation: "арбітр" },
    { word: "arcana", translation: "таємниці" },
    { word: "archetype", translation: "архетип" },
    { word: "ardor", translation: "запал" },
    { word: "argot", translation: "жаргон" },
    { word: "arrant", translation: "цілковитий" },
    { word: "asperity", translation: "суворість" },
    { word: "astringent", translation: "терпкий" },
    { word: "atavistic", translation: "атавістичний" },
    { word: "augury", translation: "пророцтво" },
    { word: "august", translation: "величний" },
    { word: "autodidact", translation: "самоук" },
    { word: "avuncular", translation: "по-дядьківськи добрий" },
    { word: "axiom", translation: "аксіома" },
    { word: "bacchanal", translation: "вакханалія" },
    { word: "bathos", translation: "антиклімакс" },
    { word: "beatific", translation: "блаженний" },
    { word: "bedizen", translation: "прикрашати" },
    { word: "beneficent", translation: "благодійний" },
    { word: "benighted", translation: "темний" },
    { word: "besmirch", translation: "заплямовувати" },
    { word: "bibulous", translation: "схильний до пияцтва" },
    { word: "biddable", translation: "слухняний" },
    { word: "bilious", translation: "жовчний" },
    { word: "blandishment", translation: "улещування" },
    { word: "blasé", translation: "збайдужілий" },
    { word: "boisterous", translation: "галасливий" },
    { word: "bowdlerize", translation: "цензурувати" },
    { word: "bumptious", translation: "самовпевнений" },
    { word: "byzantine", translation: "заплутаний" },
    { word: "cacophony", translation: "какофонія" },
    { word: "calumny", translation: "наклеп" },
    { word: "canard", translation: "вигадка" },
    { word: "captious", translation: "прискіпливий" },
    { word: "castigation", translation: "сувора критика" },
    { word: "cataclysm", translation: "катаклізм" },
    { word: "catharsis", translation: "катарсис" },
    { word: "charlatan", translation: "шарлатан" },
    { word: "chimerical", translation: "химерний" },
    { word: "circumlocution", translation: "багатослів'я" },
    { word: "cloying", translation: "нудотно-солодкий" },
    { word: "cognoscenti", translation: "знавці" },
    { word: "comport", translation: "поводитися" },
    { word: "contumacious", translation: "упертий" },
    { word: "convivial", translation: "товариський" },
    { word: "copiousness", translation: "рясність" },
    { word: "coterie", translation: "вузьке коло" },
    { word: "cynosure", translation: "центр уваги" },
    { word: "debacle", translation: "поразка" },
    { word: "decorous", translation: "пристойний" },
    { word: "deference", translation: "шанобливість" },
    { word: "demagogue", translation: "демагог" },
    { word: "denouement", translation: "розв'язка" },
    { word: "descry", translation: "помітити" },
    { word: "desiccated", translation: "висушений" },
    { word: "desuetude", translation: "занепад" },
    { word: "diaphanous", translation: "прозорий" },
    { word: "diatribe", translation: "різка критика" },
    { word: "didactic", translation: "повчальний" },
    { word: "diffident", translation: "сором'язливий" },
    { word: "dilatory", translation: "повільний" },
    { word: "disabuse", translation: "розвіювати помилку" },
    { word: "discursive", translation: "розсіяний" },
    { word: "disingenuous", translation: "нещирий" },
    { word: "dissemble", translation: "приховувати" },
    { word: "dithyramb", translation: "дифірамб" },
    { word: "dogmatic", translation: "догматичний" },
  ],
};

/**
 * Повертає випадкову підбірку слів для вказаного рівня.
 * Ніколи не повертає більше, ніж є в базі.
 */
export const pickRandomWords = (
  level: WordLevel,
  count: number,
): WordEntry[] => {
  const pool = WORDS_BY_LEVEL[level];
  return shuffle(pool).slice(0, Math.min(count, pool.length));
};
